name: Update release

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  merge-to-stable:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set git config
      run: |
        git config --local user.email "linkdotnet@action.com"
        git config --local user.name "LinkDotNet Bot"
    
    - name: Merge main to stable
      run: |
        git fetch --unshallow
        git checkout stable
        git pull
        git merge --no-ff origin/main -m "Updating to newest release"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}